site_name: Fuzz Up
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
  - mknotebooks:
      execute: True
      preamble: "docs/preamble.py"

nav:
    - Home: index.md
    - Workflow: workflow.ipynb
    - Code Reference: code_reference.md